### ISSUE TITLE
Image fails to pull mlinvoice zip file

### ISSUE THREAD

**Issue by Pekkari** [emaijala/MLInvoice-Docker#1]
Running the commands stated to have the docker version as specified in the readme,
I can observe the following:
```
Checking MLInvoice version information
Downloading https:\/\/labs.fi\/files\/mlinvoice-.zip
curl: (3) URL using bad/illegal format or missing URL
Archive:  /tmp/mlinvoice.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
```
As a result, the final container have everything setup, except the application itself,
attempting to modify config.php /usr/local/mlinvoice will show empty.

**Comment by emaijala** [comment]
Thanks for reporting the issue. It should be fixed now.
